### ISSUE TITLE
playerstats/item.json contains "stat.drop"

### ISSUE THREAD

**Issue by jemus42** [wurstmineberg/api.wurstmineberg.de#12]
The `/server/playerstats/item.json` contains a rogue stat named `stat.drop`. IIRC, this would be the summary statistic for the `drop.$item` stats and should be included in `/server/playerstats/general.json` and does not need to be in the items endpoint.

**Comment by fenhl** [comment]
The `stat.drop` stat is now listed as the `summary` field in v2.
